### ISSUE TITLE
配置文件的保存

### ISSUE THREAD

**Issue by YoYoLikesCiCi** [iHTCboy/macOSConfig#1]
请问博主这些配置文件是保存在mac的默认位置吗？还是专门新建一个文件夹？
比如vim、alfred的配置文件一般不在一起，怎么给他们在同一个仓库里同步

**Comment by iHTCboy** [comment]
@YoYoLikesCiCi 这个是我共享的仓库啊， zsh、alfred 有一些隐私的配置是隔离后才共享出来的哦。所以，如果使用，还是需要把他们放到对应的目录啊。

当然，如果你也需要一个备份创建，但不想电脑有重复的文件占用空间，你可以试试用“替身”看看能不能正常使用啊
